name: Tests

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'test/**'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pytest pytest-cov
      
      - name: Run tests
        env:
          LIBSQL_AUTH_TOKEN: ${{ secrets.LIBSQL_AUTH_TOKEN }}
          LIBSQL_URL: ${{ secrets.LIBSQL_URL }}
          SECRET: ${{ secrets.SECRET }}
          HASH: "HS256"
          LOGIN_EXPIRE: "2"
          ENV: "test"
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_BASE_URL: "https://openrouter.ai/api/v1"
          OPEN_ROUTER_MODEL: ${{ secrets.OPEN_ROUTER_MODEL }}
          SQL_MODEL: ${{ secrets.SQL_MODEL }}
          LLM_TIMEOUT: "20"
          LLM_TEMPERATURE: "0.2"
        run: |
          if [ -d "test" ] && [ -f "test/conftest.py" ]; then
            cd test
            pytest --cov --cov-branch --cov-report=xml
          else
            echo "No tests to run"
            exit 0
          fi

      - name: Upload coverage reports to Codecov
        if: success() && hashFiles('test/coverage.xml') != ''
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Jiachenyu1994/finance-ai